use inf13;

CREATE TABLE PRODUCTO (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    codigo CHAR(10) NOT NULL, 
    nombre VARCHAR(80) NOT NULL, 
    descripcion VARCHAR(200) NOT NULL,
    precio DECIMAL(10, 2) NOT NULL, 
    stock INT NOT NULL
);

CREATE TABLE CLIENTE (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    dni CHAR(8) NOT NULL, 
    nombre VARCHAR(80) NOT NULL, 
    apellidos VARCHAR(80) NOT NULL
);

CREATE TABLE CARRITO (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idCliente INT NOT NULL,
    nombre VARCHAR(80) NULL, 
    fecha DATE NOT NULL
);

ALTER TABLE CARRITO
	ADD CONSTRAINT FK_CARRITO_CLIENTE
		FOREIGN KEY CARRITO(idCliente) REFERENCES CLIENTE(id);

CREATE TABLE ITEMCARRITO (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    idCarrito INT NOT NULL, 
    idProducto INT NOT NULL, 
    cantidad INT NOT NULL, 
    subTotal DECIMAL(10, 2) NOT NULL
);

ALTER TABLE ITEMCARRITO 
	ADD CONSTRAINT FK_ITEMCARRITO_CARRITO
		FOREIGN KEY ITEMCARRITO(idCarrito) REFERENCES CARRITO(id); 

ALTER TABLE ITEMCARRITO
	ADD CONSTRAINT FK_ITEMCARRITO_PRODUCTO
		FOREIGN KEY ITEMCARRITO(idProducto) REFERENCES PRODUCTO(id);
        
CREATE TABLE ORDEN (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    numero CHAR(10) NULL, 
    idCarrito INT NOT NULL, 
    fecha DATE NOT NULL, 
    subTotal DECIMAL(10, 2) NOT NULL, 
    igv DECIMAL(10, 2) NOT NULL, 
    total DECIMAL(10, 2) NOT NULL
);

ALTER TABLE ORDEN
	ADD CONSTRAINT FK_ORDEN_CARRITO
		FOREIGN KEY ORDEN(idCarrito) REFERENCES CARRITO(id);

CREATE TABLE ITEMORDEN (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    idOrden INT NOT NULL, 
    idProducto INT NOT NULL, 
    cantidad INT NOT NULL, 
    subTotal DECIMAL(10, 2) NOT NULL
);

ALTER TABLE ITEMORDEN
	ADD CONSTRAINT FK_ITEMORDEN_ORDEN
		FOREIGN KEY ITEMORDEN(idOrden) REFERENCES ORDEN(id);
        
ALTER TABLE ITEMORDEN
	ADD CONSTRAINT FK_ITEMORDEN_PRODUCTO
		FOREIGN KEY ITEMORDEN(idProducto) REFERENCES PRODUCTO(id);